name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_DIR: build
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create build directory
      run: mkdir -p ${{env.BUILD_DIR}}

    - name: Configure CMake
      working-directory: ${{env.BUILD_DIR}}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build with CMake
      working-directory: ${{env.BUILD_DIR}}
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Run tests (optional)
      working-directory: ${{env.BUILD_DIR}}
      run: ctest --output-on-failure
